### ISSUE TITLE
Error while running GET service info

### ISSUE THREAD

**Issue by pranky89** [beniz/quick_cdiscount#2]
Hello, i m using the following command to create the service.

`root@cv:~/dev/deepdetect/build# curl -X PUT "http://localhost:8080/services/p" -d "{\"mllib\":\"caffe\",\"description\":\"pankaj classification service\",\"type\":\"supervised\",\"parameters\":{\"input\":{\"connector\":\"image\",\"width\":224,\"height\":224},\"mllib\":{\"template\":\"mlp\",\"nclasses\":5,\"layers\":[512,512,512],\"activation\":\"prelu\"}},\"model\":{\"templates\":\"../templates/caffe/\",\"repository\":\"../../../test_images\"}}"`

Using the following command to train the service

```
curl -X POST "http://localhost:8080/train" -d "{\"service\":\"p\",\"async\":true,\"parameters\":{\"mllib\":{\"gpu\":false,\"net\":{\"batch_size\":32},\"solver\":{\"test_interval\":500,\"iterations\":30000,\"base_lr\":0.001,\"stepsize\":1000,\"gamma\":0.9}},\"input\":{\"connector\":\"image\",\"test_split\":0.1,\"shuffle\":true,\"width\":224,\"height\":224},\"output\":{\"measure\":[\"acc\",\"mcll\",\"f1\"]}},\"data\":[\"../../../test_images\"]}"

```

In the dede logs, i can see that it started working on the images directory(attached is the dede log from console output)
[dede-errorlog.txt](https://github.com/beniz/quick_cdiscount/files/231719/dede-errorlog.txt)

And then, if i run the GET training service info, it crashes the Training job with the error:

`curl -X GET "http://localhost:8080/train?service=p&job=1"`

---

INFO - 20:11:47 - Solver scaffolding done.
INFO - 20:11:47 - Ignoring source layer inputl
INFO - 20:11:47 - Ignoring source layer loss
INFO - 20:11:47 - Opened lmdb ../../../test_images/test.lmdb

> ERROR - 20:12:32 - service p training status call failed
> 
> ERROR - 20:12:32 - {"code":500,"msg":"InternalError","dd_code":1007,"dd_msg":"src/caffe/data_transformer.cpp:177 / Check failed (custom): (datum_height) == (height)"}

If i don't run the check training service info call, i can see the screen is stuck at the following lines in dede console logs:

```
INFO - 20:12:59 - act0 does not need backward computation.
INFO - 20:12:59 - ip0 does not need backward computation.
INFO - 20:12:59 - inputlt does not need backward computation.
INFO - 20:12:59 - This network produces output label
INFO - 20:12:59 - This network produces output losst
INFO - 20:12:59 - Network initialization done.
INFO - 20:12:59 - Solver scaffolding done.
INFO - 20:12:59 - Ignoring source layer inputl
INFO - 20:12:59 - Ignoring source layer loss
```

Does it mean its still running and meanwhile, i should not run any check call?
Please assist, thanks

**Comment by pranky89** [comment]
Posted in wrong place, moved to Deepdetect GIT issues page.
Closing this.

**Comment by beniz** [comment]
The `GET` call simply reveals the error of the asynchronous training call. Your problem is with the size of data, as pointed by the `(custom): (datum_height) == (height)` error.

**Comment by beniz** [comment]
if you are not using the cdiscount model, yes, let's close it here.
